{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecr-optimizer.serviceAccountName" . }}
  labels:
    {{- include "ecr-optimizer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.aws.useIRSA }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
{{- end }}
{{- end }}

