apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecr-optimizer.fullname" . }}-backend
  labels:
    {{- include "ecr-optimizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecr-optimizer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- if eq .Values.deploymentPattern "separate" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecr-optimizer.fullname" . }}-frontend
  labels:
    {{- include "ecr-optimizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecr-optimizer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecr-optimizer.fullname" . }}-frontend
  labels:
    {{- include "ecr-optimizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http-frontend
      protocol: TCP
      name: http
  selector:
    {{- include "ecr-optimizer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}

