apiVersion: v1
entries:
  ecr-optimizer:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 0.1.2
    created: "2025-12-05T10:29:27.569856575Z"
    description: ECR Optimizer - AWS ECR image management tool
    digest: d4ecf8f89fde8b7b1dcae7936272724903311b0c6b420b1079762595ab16cce5
    home: https://github.com/kaskol10/ecr-optimizer
    keywords:
    - aws
    - ecr
    - container
    - optimization
    - cost-reduction
    - docker
    - image-management
    maintainers:
    - name: ECR Optimizer Contributors
    name: ecr-optimizer
    sources:
    - https://github.com/kaskol10/ecr-optimizer
    type: application
    urls:
    - https://kaskol10.github.io/ecr-optimizer/charts/ecr-optimizer-0.1.2.tgz
    version: 0.1.2
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 0.1.1
    created: "2025-12-05T10:29:27.569403002Z"
    description: ECR Optimizer - AWS ECR image management tool
    digest: 65168d4f957d5073455be44987654e876fa12f556b7bcd13d72e9b287375fc8f
    home: https://github.com/kaskol10/ecr-optimizer
    keywords:
    - aws
    - ecr
    - container
    - optimization
    - cost-reduction
    - docker
    - image-management
    maintainers:
    - name: ECR Optimizer Contributors
    name: ecr-optimizer
    sources:
    - https://github.com/kaskol10/ecr-optimizer
    type: application
    urls:
    - https://kaskol10.github.io/ecr-optimizer/charts/ecr-optimizer-0.1.1.tgz
    version: 0.1.1
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-05T10:29:27.56892838Z"
    description: ECR Optimizer - AWS ECR image management tool
    digest: b502c3515f3d81d4cdf6dcf7948a35f724dfbceaf0828400ca7b85f51e3a342a
    home: https://github.com/kaskol10/ecr-optimizer
    keywords:
    - aws
    - ecr
    - container
    - optimization
    - cost-reduction
    - docker
    - image-management
    maintainers:
    - name: ECR Optimizer Contributors
    name: ecr-optimizer
    sources:
    - https://github.com/kaskol10/ecr-optimizer
    type: application
    urls:
    - https://kaskol10.github.io/ecr-optimizer/charts/ecr-optimizer-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-05T10:29:27.568284392Z"
