apiVersion: v1
entries:
  ecr-optimizer:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-05T10:20:46.287939864Z"
    description: ECR Optimizer - AWS ECR image management tool
    digest: f832e5536a105ca878f8a830a083a9e666d130157be66ff46df0393e0375f134
    home: https://github.com/kaskol10/ecr-optimizer
    keywords:
    - aws
    - ecr
    - container
    - optimization
    - cost-reduction
    - docker
    - image-management
    maintainers:
    - name: ECR Optimizer Contributors
    name: ecr-optimizer
    sources:
    - https://github.com/kaskol10/ecr-optimizer
    type: application
    urls:
    - https://kaskol10.github.io/ecr-optimizer/charts/ecr-optimizer-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-05T10:20:46.287242912Z"
